import type { TcgCard } from "./types";

/** Images and metadata sourced from the Pokémon TCG API (images.pokemontcg.io). */
const img = (set: string, num: string) => `https://images.pokemontcg.io/${set}/${num}.png`;

export const CARDS: TcgCard[] = [
  {
    id: "base1-4",
    name: "Charizard",
    game: "pokemon",
    language: "EN",
    setName: "Base Set",
    setCode: "BS",
    number: "004",
    rarity: "Rare Holo",
    type: "Fire",
    hp: 120,
    artist: "Mitsuhiro Arita",
    image: img("base1", "4"),
    marketPrice: 0,
    change7d: null,
    variants: ["Unlimited", "Shadowless", "1st Edition"],
  },
  {
    id: "swsh7-215",
    name: "Umbreon VMAX",
    game: "pokemon",
    language: "EN",
    setName: "Evolving Skies",
    setCode: "EVS",
    number: "215",
    rarity: "Alternate Art Secret",
    type: "Darkness",
    hp: 310,
    artist: "KEIICHIRO ITO",
    image: img("swsh7", "215"),
    marketPrice: 0,
    change7d: null,
    variants: ["Rainbow Rare", "Alternate Art"],
  },
  {
    id: "sv8pt5-161",
    name: "Umbreon ex",
    game: "pokemon",
    language: "EN",
    setName: "Prismatic Evolutions",
    setCode: "PRE",
    number: "161",
    rarity: "Special Illustration Rare",
    type: "Darkness",
    hp: 280,
    image: img("sv8pt5", "161"),
    marketPrice: 0,
    change7d: null,
    variants: ["Double Rare", "Special Illustration Rare"],
  },
  {
    id: "sv2-269",
    name: "Iono",
    game: "pokemon",
    language: "EN",
    setName: "Paldea Evolved",
    setCode: "PAL",
    number: "269",
    rarity: "Special Illustration Rare",
    artist: "kirisAki",
    image: img("sv2", "269"),
    marketPrice: 0,
    change7d: null,
    variants: ["Ultra Rare", "Special Illustration Rare"],
  },
  {
    id: "sv1-245",
    name: "Gardevoir ex",
    game: "pokemon",
    language: "EN",
    setName: "Scarlet & Violet",
    setCode: "SVI",
    number: "245",
    rarity: "Special Illustration Rare",
    type: "Psychic",
    hp: 310,
    artist: "Jiro Sasumo",
    image: img("sv1", "245"),
    marketPrice: 0,
    change7d: null,
    variants: ["Double Rare", "Ultra Rare", "Special Illustration Rare"],
  },
  {
    id: "swsh4-44",
    name: "Pikachu VMAX",
    game: "pokemon",
    language: "EN",
    setName: "Vivid Voltage",
    setCode: "VIV",
    number: "044",
    rarity: "Rare Holo VMAX",
    type: "Lightning",
    hp: 310,
    artist: "aky CG Works",
    image: img("swsh4", "44"),
    marketPrice: 0,
    change7d: null,
    variants: ["Normal", "Rainbow Rare"],
  },
  {
    id: "swsh35-74",
    name: "Charizard VMAX",
    game: "pokemon",
    language: "EN",
    setName: "Champion's Path",
    setCode: "CPA",
    number: "074",
    rarity: "Rare Rainbow",
    type: "Fire",
    hp: 330,
    artist: "aky CG Works",
    image: img("swsh35", "74"),
    marketPrice: 0,
    change7d: null,
  },
  {
    id: "sm115-9",
    name: "Charizard-GX",
    game: "pokemon",
    language: "EN",
    setName: "Hidden Fates",
    setCode: "HIF",
    number: "009",
    rarity: "Rare Holo GX",
    type: "Fire",
    hp: 250,
    artist: "aky CG Works",
    image: img("sm115", "9"),
    marketPrice: 0,
    change7d: null,
  },
  {
    id: "sv9-69",
    name: "Mimikyu ex",
    game: "pokemon",
    language: "EN",
    setName: "Journey Together",
    setCode: "JTG",
    number: "069",
    rarity: "Double Rare",
    type: "Psychic",
    hp: 190,
    artist: "PLANETA Igarashi",
    image: img("sv9", "69"),
    marketPrice: 0,
    change7d: null,
  },
  {
    id: "jp-sv2p-091",
    name: "Iono",
    nativeName: "ナンジャモ",
    game: "pokemon",
    language: "JP",
    setName: "Snow Hazard",
    setCode: "SV2P",
    number: "091",
    rarity: "Special Art Rare",
    artist: "kirisAki",
    image: img("sv4pt5", "237"),
    marketPrice: 0,
    change7d: null,
    variants: ["Super Rare", "Special Art Rare"],
  },
  {
    id: "jp-s9-069",
    name: "Mimikyu VMAX",
    nativeName: "ミミッキュVMAX",
    game: "pokemon",
    language: "JP",
    setName: "Star Birth",
    setCode: "S9",
    number: "069",
    rarity: "Art Rare",
    type: "Psychic",
    hp: 300,
    artist: "Naoki Saito",
    image: img("swsh9tg", "TG17"),
    marketPrice: 0,
    change7d: null,
    variants: ["Normal", "Art Rare"],
  },
  {
    id: "jp-s12a-215",
    name: "Umbreon VMAX",
    nativeName: "ブラッキーVMAX",
    game: "pokemon",
    language: "JP",
    setName: "VSTAR Universe",
    setCode: "S12A",
    number: "215",
    rarity: "Special Art Rare",
    type: "Darkness",
    hp: 310,
    artist: "AKIRA EGAWA",
    image: img("swsh7", "214"),
    marketPrice: 0,
    change7d: null,
  },
  {
    id: "jp-sv1a-086",
    name: "Gardevoir ex",
    nativeName: "サーナイトex",
    game: "pokemon",
    language: "JP",
    setName: "Triplet Beat",
    setCode: "SV1A",
    number: "086",
    rarity: "Super Rare",
    type: "Psychic",
    hp: 310,
    artist: "N-DESIGN Inc.",
    image: img("sv1", "228"),
    marketPrice: 0,
    change7d: null,
  },
  {
    id: "jp-sv8-060",
    name: "Umbreon ex",
    nativeName: "ブラッキーex",
    game: "pokemon",
    language: "JP",
    setName: "Terastal Festival",
    setCode: "SV8A",
    number: "060",
    rarity: "Double Rare",
    type: "Darkness",
    hp: 280,
    image: img("sv8pt5", "60"),
    marketPrice: 0,
    change7d: null,
  },
];

export const CARD_BY_ID = new Map(CARDS.map((c) => [c.id, c]));

/** Cards fetched from the live catalogue are cached here so collection views resolve them. */
export function registerCards(cards: TcgCard[]) {
  for (const c of cards) CARD_BY_ID.set(c.id, c);
}

export function getCard(id: string) {
  return CARD_BY_ID.get(id);
}
