import type { TcgCard } from "./types";

const img = (set: string, num: string) => `https://images.pokemontcg.io/${set}/${num}.png`;

export const CARDS: TcgCard[] = [
  {
    id: "sv3pt5-025",
    name: "Pikachu",
    game: "pokemon",
    language: "EN",
    setName: "151",
    setCode: "MEW",
    number: "025",
    rarity: "Illustration Rare",
    type: "Lightning",
    hp: 60,
    artist: "Yuka Morii",
    image: img("sv3pt5", "173"),
    marketPrice: 42.5,
    change7d: 4.2,
    variants: ["Normal", "Reverse Holo", "Illustration Rare"],
  },
  {
    id: "sv3pt5-006",
    name: "Charizard ex",
    game: "pokemon",
    language: "EN",
    setName: "151",
    setCode: "MEW",
    number: "006",
    rarity: "Double Rare",
    type: "Fire",
    hp: 330,
    artist: "5ban Graphics",
    image: img("sv3pt5", "6"),
    marketPrice: 28.9,
    change7d: -2.1,
    variants: ["Normal", "Special Illustration Rare"],
  },
  {
    id: "sv4p-025",
    name: "Mimikyu",
    nativeName: "ミミッキュ",
    game: "pokemon",
    language: "JP",
    setName: "Paradigm Trigger",
    setCode: "SV4P",
    number: "025",
    rarity: "Art Rare",
    type: "Psychic",
    hp: 70,
    artist: "Saya Tsuruta",
    image: img("swsh12pt5", "68"),
    marketPrice: 63.75,
    change7d: 9.6,
    variants: ["Normal", "Art Rare", "Special Art Rare"],
  },
  {
    id: "base1-004",
    name: "Charizard",
    game: "pokemon",
    language: "EN",
    setName: "Base Set",
    setCode: "BS",
    number: "004",
    rarity: "Holo Rare",
    type: "Fire",
    hp: 120,
    artist: "Mitsuhiro Arita",
    image: img("base1", "4"),
    marketPrice: 412,
    change7d: 1.4,
    variants: ["Unlimited", "1st Edition", "Shadowless"],
  },
  {
    id: "swsh4-044",
    name: "Pikachu VMAX",
    game: "pokemon",
    language: "EN",
    setName: "Vivid Voltage",
    setCode: "VIV",
    number: "044",
    rarity: "Ultra Rare",
    type: "Lightning",
    hp: 310,
    artist: "aky CG Works",
    image: img("swsh4", "44"),
    marketPrice: 34.1,
    change7d: -5.4,
    variants: ["Normal", "Rainbow Rare"],
  },
  {
    id: "sv2-245",
    name: "Iono",
    nativeName: "ナンジャモ",
    game: "pokemon",
    language: "JP",
    setName: "Snow Hazard",
    setCode: "SV2P",
    number: "091",
    rarity: "Special Art Rare",
    artist: "Saboteri",
    image: img("sv2", "254"),
    marketPrice: 118.4,
    change7d: 12.8,
    variants: ["Normal", "Super Rare", "Special Art Rare"],
  },
  {
    id: "swsh12pt5-160",
    name: "Lugia V",
    game: "pokemon",
    language: "EN",
    setName: "Crown Zenith",
    setCode: "CRZ",
    number: "GG60",
    rarity: "Galarian Gallery",
    type: "Colorless",
    hp: 220,
    artist: "Ryota Murayama",
    image: img("swsh12pt5", "GG60"),
    marketPrice: 21.3,
    change7d: 0.6,
  },
  {
    id: "sv1-197",
    name: "Miriam",
    game: "pokemon",
    language: "EN",
    setName: "Scarlet & Violet",
    setCode: "SVI",
    number: "197",
    rarity: "Illustration Rare",
    artist: "Yuu Nishida",
    image: img("sv1", "197"),
    marketPrice: 15.7,
    change7d: 3.3,
  },
  {
    id: "sv4-232",
    name: "Gardevoir ex",
    game: "pokemon",
    language: "EN",
    setName: "Paradox Rift",
    setCode: "PAR",
    number: "233",
    rarity: "Special Illustration Rare",
    type: "Psychic",
    hp: 310,
    artist: "AKIRA EGAWA",
    image: img("sv4", "233"),
    marketPrice: 88.2,
    change7d: -1.9,
  },
  {
    id: "swsh9-069",
    name: "Umbreon VMAX",
    game: "pokemon",
    language: "EN",
    setName: "Evolving Skies",
    setCode: "EVS",
    number: "215",
    rarity: "Alternate Art",
    type: "Darkness",
    hp: 310,
    artist: "Hasuno",
    image: img("swsh7", "215"),
    marketPrice: 512.6,
    change7d: 6.1,
  },
  {
    id: "s12a-198",
    name: "Rayquaza VMAX",
    nativeName: "レックウザVMAX",
    game: "pokemon",
    language: "JP",
    setName: "VSTAR Universe",
    setCode: "S12A",
    number: "198",
    rarity: "Special Art Rare",
    type: "Dragon",
    hp: 320,
    artist: "Ryuta Fuse",
    image: img("swsh7", "218"),
    marketPrice: 149.9,
    change7d: 7.4,
  },
  {
    id: "sv3-125",
    name: "Chien-Pao ex",
    game: "pokemon",
    language: "EN",
    setName: "Paldea Evolved",
    setCode: "PAL",
    number: "261",
    rarity: "Special Illustration Rare",
    type: "Water",
    hp: 220,
    artist: "Shinji Kanda",
    image: img("sv2", "261"),
    marketPrice: 37.8,
    change7d: -3.2,
  },
];

export const CARD_BY_ID = new Map(CARDS.map((c) => [c.id, c]));

export function getCard(id: string) {
  return CARD_BY_ID.get(id);
}
