/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as DatabaseRouteImport } from './routes/database'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as TradesRouteImport } from './routes/trades'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as CardCardIdRouteImport } from './routes/card.$cardId'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiPublicRefreshPricesRouteImport } from './routes/api/public/refresh-prices'
import { Route as ApiPublicSyncCatalogRouteImport } from './routes/api/public/sync-catalog'
import { Route as ApiPublicSyncEbayRouteImport } from './routes/api/public/sync-ebay'
import { Route as ApiPublicSyncJpEnglishRouteImport } from './routes/api/public/sync-jp-english'
import { Route as ApiPublicSyncJpImagesRouteImport } from './routes/api/public/sync-jp-images'
import { Route as ApiPublicSyncJpNamesRouteImport } from './routes/api/public/sync-jp-names'
import { Route as ApiPublicSyncMissingSetsRouteImport } from './routes/api/public/sync-missing-sets'
import { Route as ApiPublicSyncPokewalletRouteImport } from './routes/api/public/sync-pokewallet'
import { Route as ApiPublicSyncPricesRouteImport } from './routes/api/public/sync-prices'
import { Route as ApiPublicSyncPtcgRouteImport } from './routes/api/public/sync-ptcg'
import { Route as ApiPublicSyncTcgdexRouteImport } from './routes/api/public/sync-tcgdex'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabaseRoute = DatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const TradesRoute = TradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CardCardIdRoute = CardCardIdRouteImport.update({
  id: '/card/$cardId',
  path: '/card/$cardId',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRefreshPricesRoute = ApiPublicRefreshPricesRouteImport.update({
  id: '/api/public/refresh-prices',
  path: '/api/public/refresh-prices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncCatalogRoute = ApiPublicSyncCatalogRouteImport.update({
  id: '/api/public/sync-catalog',
  path: '/api/public/sync-catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncEbayRoute = ApiPublicSyncEbayRouteImport.update({
  id: '/api/public/sync-ebay',
  path: '/api/public/sync-ebay',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncJpEnglishRoute = ApiPublicSyncJpEnglishRouteImport.update({
  id: '/api/public/sync-jp-english',
  path: '/api/public/sync-jp-english',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncJpImagesRoute = ApiPublicSyncJpImagesRouteImport.update({
  id: '/api/public/sync-jp-images',
  path: '/api/public/sync-jp-images',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncJpNamesRoute = ApiPublicSyncJpNamesRouteImport.update({
  id: '/api/public/sync-jp-names',
  path: '/api/public/sync-jp-names',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncMissingSetsRoute =
  ApiPublicSyncMissingSetsRouteImport.update({
    id: '/api/public/sync-missing-sets',
    path: '/api/public/sync-missing-sets',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSyncPokewalletRoute = ApiPublicSyncPokewalletRouteImport.update({
  id: '/api/public/sync-pokewallet',
  path: '/api/public/sync-pokewallet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncPricesRoute = ApiPublicSyncPricesRouteImport.update({
  id: '/api/public/sync-prices',
  path: '/api/public/sync-prices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncPtcgRoute = ApiPublicSyncPtcgRouteImport.update({
  id: '/api/public/sync-ptcg',
  path: '/api/public/sync-ptcg',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncTcgdexRoute = ApiPublicSyncTcgdexRouteImport.update({
  id: '/api/public/sync-tcgdex',
  path: '/api/public/sync-tcgdex',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/collection': typeof CollectionRoute
  '/database': typeof DatabaseRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scan': typeof ScanRoute
  '/trades': typeof TradesRoute
  '/trends': typeof TrendsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/account': typeof AuthenticatedAccountRoute
  '/card/$cardId': typeof CardCardIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/refresh-prices': typeof ApiPublicRefreshPricesRoute
  '/api/public/sync-catalog': typeof ApiPublicSyncCatalogRoute
  '/api/public/sync-ebay': typeof ApiPublicSyncEbayRoute
  '/api/public/sync-jp-english': typeof ApiPublicSyncJpEnglishRoute
  '/api/public/sync-jp-images': typeof ApiPublicSyncJpImagesRoute
  '/api/public/sync-jp-names': typeof ApiPublicSyncJpNamesRoute
  '/api/public/sync-missing-sets': typeof ApiPublicSyncMissingSetsRoute
  '/api/public/sync-pokewallet': typeof ApiPublicSyncPokewalletRoute
  '/api/public/sync-prices': typeof ApiPublicSyncPricesRoute
  '/api/public/sync-ptcg': typeof ApiPublicSyncPtcgRoute
  '/api/public/sync-tcgdex': typeof ApiPublicSyncTcgdexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/collection': typeof CollectionRoute
  '/database': typeof DatabaseRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scan': typeof ScanRoute
  '/trades': typeof TradesRoute
  '/trends': typeof TrendsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/account': typeof AuthenticatedAccountRoute
  '/card/$cardId': typeof CardCardIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/refresh-prices': typeof ApiPublicRefreshPricesRoute
  '/api/public/sync-catalog': typeof ApiPublicSyncCatalogRoute
  '/api/public/sync-ebay': typeof ApiPublicSyncEbayRoute
  '/api/public/sync-jp-english': typeof ApiPublicSyncJpEnglishRoute
  '/api/public/sync-jp-images': typeof ApiPublicSyncJpImagesRoute
  '/api/public/sync-jp-names': typeof ApiPublicSyncJpNamesRoute
  '/api/public/sync-missing-sets': typeof ApiPublicSyncMissingSetsRoute
  '/api/public/sync-pokewallet': typeof ApiPublicSyncPokewalletRoute
  '/api/public/sync-prices': typeof ApiPublicSyncPricesRoute
  '/api/public/sync-ptcg': typeof ApiPublicSyncPtcgRoute
  '/api/public/sync-tcgdex': typeof ApiPublicSyncTcgdexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/collection': typeof CollectionRoute
  '/database': typeof DatabaseRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scan': typeof ScanRoute
  '/trades': typeof TradesRoute
  '/trends': typeof TrendsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/card/$cardId': typeof CardCardIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/refresh-prices': typeof ApiPublicRefreshPricesRoute
  '/api/public/sync-catalog': typeof ApiPublicSyncCatalogRoute
  '/api/public/sync-ebay': typeof ApiPublicSyncEbayRoute
  '/api/public/sync-jp-english': typeof ApiPublicSyncJpEnglishRoute
  '/api/public/sync-jp-images': typeof ApiPublicSyncJpImagesRoute
  '/api/public/sync-jp-names': typeof ApiPublicSyncJpNamesRoute
  '/api/public/sync-missing-sets': typeof ApiPublicSyncMissingSetsRoute
  '/api/public/sync-pokewallet': typeof ApiPublicSyncPokewalletRoute
  '/api/public/sync-prices': typeof ApiPublicSyncPricesRoute
  '/api/public/sync-ptcg': typeof ApiPublicSyncPtcgRoute
  '/api/public/sync-tcgdex': typeof ApiPublicSyncTcgdexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/collection'
    | '/database'
    | '/mcp'
    | '/onboarding'
    | '/profile'
    | '/reset-password'
    | '/scan'
    | '/trades'
    | '/trends'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/account'
    | '/card/$cardId'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/refresh-prices'
    | '/api/public/sync-catalog'
    | '/api/public/sync-ebay'
    | '/api/public/sync-jp-english'
    | '/api/public/sync-jp-images'
    | '/api/public/sync-jp-names'
    | '/api/public/sync-missing-sets'
    | '/api/public/sync-pokewallet'
    | '/api/public/sync-prices'
    | '/api/public/sync-ptcg'
    | '/api/public/sync-tcgdex'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/collection'
    | '/database'
    | '/mcp'
    | '/onboarding'
    | '/profile'
    | '/reset-password'
    | '/scan'
    | '/trades'
    | '/trends'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/account'
    | '/card/$cardId'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/refresh-prices'
    | '/api/public/sync-catalog'
    | '/api/public/sync-ebay'
    | '/api/public/sync-jp-english'
    | '/api/public/sync-jp-images'
    | '/api/public/sync-jp-names'
    | '/api/public/sync-missing-sets'
    | '/api/public/sync-pokewallet'
    | '/api/public/sync-prices'
    | '/api/public/sync-ptcg'
    | '/api/public/sync-tcgdex'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/collection'
    | '/database'
    | '/mcp'
    | '/onboarding'
    | '/profile'
    | '/reset-password'
    | '/scan'
    | '/trades'
    | '/trends'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/account'
    | '/card/$cardId'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/refresh-prices'
    | '/api/public/sync-catalog'
    | '/api/public/sync-ebay'
    | '/api/public/sync-jp-english'
    | '/api/public/sync-jp-images'
    | '/api/public/sync-jp-names'
    | '/api/public/sync-missing-sets'
    | '/api/public/sync-pokewallet'
    | '/api/public/sync-prices'
    | '/api/public/sync-ptcg'
    | '/api/public/sync-tcgdex'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CollectionRoute: typeof CollectionRoute
  DatabaseRoute: typeof DatabaseRoute
  McpRoute: typeof McpRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ScanRoute: typeof ScanRoute
  TradesRoute: typeof TradesRoute
  TrendsRoute: typeof TrendsRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  CardCardIdRoute: typeof CardCardIdRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicRefreshPricesRoute: typeof ApiPublicRefreshPricesRoute
  ApiPublicSyncCatalogRoute: typeof ApiPublicSyncCatalogRoute
  ApiPublicSyncEbayRoute: typeof ApiPublicSyncEbayRoute
  ApiPublicSyncJpEnglishRoute: typeof ApiPublicSyncJpEnglishRoute
  ApiPublicSyncJpImagesRoute: typeof ApiPublicSyncJpImagesRoute
  ApiPublicSyncJpNamesRoute: typeof ApiPublicSyncJpNamesRoute
  ApiPublicSyncMissingSetsRoute: typeof ApiPublicSyncMissingSetsRoute
  ApiPublicSyncPokewalletRoute: typeof ApiPublicSyncPokewalletRoute
  ApiPublicSyncPricesRoute: typeof ApiPublicSyncPricesRoute
  ApiPublicSyncPtcgRoute: typeof ApiPublicSyncPtcgRoute
  ApiPublicSyncTcgdexRoute: typeof ApiPublicSyncTcgdexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/database': {
      id: '/database'
      path: '/database'
      fullPath: '/database'
      preLoaderRoute: typeof DatabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trades': {
      id: '/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof TradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/card/$cardId': {
      id: '/card/$cardId'
      path: '/card/$cardId'
      fullPath: '/card/$cardId'
      preLoaderRoute: typeof CardCardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/refresh-prices': {
      id: '/api/public/refresh-prices'
      path: '/api/public/refresh-prices'
      fullPath: '/api/public/refresh-prices'
      preLoaderRoute: typeof ApiPublicRefreshPricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-catalog': {
      id: '/api/public/sync-catalog'
      path: '/api/public/sync-catalog'
      fullPath: '/api/public/sync-catalog'
      preLoaderRoute: typeof ApiPublicSyncCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-ebay': {
      id: '/api/public/sync-ebay'
      path: '/api/public/sync-ebay'
      fullPath: '/api/public/sync-ebay'
      preLoaderRoute: typeof ApiPublicSyncEbayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-jp-english': {
      id: '/api/public/sync-jp-english'
      path: '/api/public/sync-jp-english'
      fullPath: '/api/public/sync-jp-english'
      preLoaderRoute: typeof ApiPublicSyncJpEnglishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-jp-images': {
      id: '/api/public/sync-jp-images'
      path: '/api/public/sync-jp-images'
      fullPath: '/api/public/sync-jp-images'
      preLoaderRoute: typeof ApiPublicSyncJpImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-jp-names': {
      id: '/api/public/sync-jp-names'
      path: '/api/public/sync-jp-names'
      fullPath: '/api/public/sync-jp-names'
      preLoaderRoute: typeof ApiPublicSyncJpNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-missing-sets': {
      id: '/api/public/sync-missing-sets'
      path: '/api/public/sync-missing-sets'
      fullPath: '/api/public/sync-missing-sets'
      preLoaderRoute: typeof ApiPublicSyncMissingSetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-pokewallet': {
      id: '/api/public/sync-pokewallet'
      path: '/api/public/sync-pokewallet'
      fullPath: '/api/public/sync-pokewallet'
      preLoaderRoute: typeof ApiPublicSyncPokewalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-prices': {
      id: '/api/public/sync-prices'
      path: '/api/public/sync-prices'
      fullPath: '/api/public/sync-prices'
      preLoaderRoute: typeof ApiPublicSyncPricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-ptcg': {
      id: '/api/public/sync-ptcg'
      path: '/api/public/sync-ptcg'
      fullPath: '/api/public/sync-ptcg'
      preLoaderRoute: typeof ApiPublicSyncPtcgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-tcgdex': {
      id: '/api/public/sync-tcgdex'
      path: '/api/public/sync-tcgdex'
      fullPath: '/api/public/sync-tcgdex'
      preLoaderRoute: typeof ApiPublicSyncTcgdexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CollectionRoute: CollectionRoute,
  DatabaseRoute: DatabaseRoute,
  McpRoute: McpRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ScanRoute: ScanRoute,
  TradesRoute: TradesRoute,
  TrendsRoute: TrendsRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  CardCardIdRoute: CardCardIdRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicRefreshPricesRoute: ApiPublicRefreshPricesRoute,
  ApiPublicSyncCatalogRoute: ApiPublicSyncCatalogRoute,
  ApiPublicSyncEbayRoute: ApiPublicSyncEbayRoute,
  ApiPublicSyncJpEnglishRoute: ApiPublicSyncJpEnglishRoute,
  ApiPublicSyncJpImagesRoute: ApiPublicSyncJpImagesRoute,
  ApiPublicSyncJpNamesRoute: ApiPublicSyncJpNamesRoute,
  ApiPublicSyncMissingSetsRoute: ApiPublicSyncMissingSetsRoute,
  ApiPublicSyncPokewalletRoute: ApiPublicSyncPokewalletRoute,
  ApiPublicSyncPricesRoute: ApiPublicSyncPricesRoute,
  ApiPublicSyncPtcgRoute: ApiPublicSyncPtcgRoute,
  ApiPublicSyncTcgdexRoute: ApiPublicSyncTcgdexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
