/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as DatabaseRouteImport } from './routes/database'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as CardCardIdRouteImport } from './routes/card.$cardId'
import { Route as ApiPublicRefreshPricesRouteImport } from './routes/api/public/refresh-prices'
import { Route as ApiPublicSyncCatalogRouteImport } from './routes/api/public/sync-catalog'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabaseRoute = DatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const CardCardIdRoute = CardCardIdRouteImport.update({
  id: '/card/$cardId',
  path: '/card/$cardId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRefreshPricesRoute = ApiPublicRefreshPricesRouteImport.update({
  id: '/api/public/refresh-prices',
  path: '/api/public/refresh-prices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncCatalogRoute = ApiPublicSyncCatalogRouteImport.update({
  id: '/api/public/sync-catalog',
  path: '/api/public/sync-catalog',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/collection': typeof CollectionRoute
  '/database': typeof DatabaseRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/scan': typeof ScanRoute
  '/trends': typeof TrendsRoute
  '/card/$cardId': typeof CardCardIdRoute
  '/api/public/refresh-prices': typeof ApiPublicRefreshPricesRoute
  '/api/public/sync-catalog': typeof ApiPublicSyncCatalogRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/collection': typeof CollectionRoute
  '/database': typeof DatabaseRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/scan': typeof ScanRoute
  '/trends': typeof TrendsRoute
  '/card/$cardId': typeof CardCardIdRoute
  '/api/public/refresh-prices': typeof ApiPublicRefreshPricesRoute
  '/api/public/sync-catalog': typeof ApiPublicSyncCatalogRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/collection': typeof CollectionRoute
  '/database': typeof DatabaseRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/scan': typeof ScanRoute
  '/trends': typeof TrendsRoute
  '/card/$cardId': typeof CardCardIdRoute
  '/api/public/refresh-prices': typeof ApiPublicRefreshPricesRoute
  '/api/public/sync-catalog': typeof ApiPublicSyncCatalogRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/collection'
    | '/database'
    | '/onboarding'
    | '/profile'
    | '/scan'
    | '/trends'
    | '/card/$cardId'
    | '/api/public/refresh-prices'
    | '/api/public/sync-catalog'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/collection'
    | '/database'
    | '/onboarding'
    | '/profile'
    | '/scan'
    | '/trends'
    | '/card/$cardId'
    | '/api/public/refresh-prices'
    | '/api/public/sync-catalog'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/collection'
    | '/database'
    | '/onboarding'
    | '/profile'
    | '/scan'
    | '/trends'
    | '/card/$cardId'
    | '/api/public/refresh-prices'
    | '/api/public/sync-catalog'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CollectionRoute: typeof CollectionRoute
  DatabaseRoute: typeof DatabaseRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  ScanRoute: typeof ScanRoute
  TrendsRoute: typeof TrendsRoute
  CardCardIdRoute: typeof CardCardIdRoute
  ApiPublicRefreshPricesRoute: typeof ApiPublicRefreshPricesRoute
  ApiPublicSyncCatalogRoute: typeof ApiPublicSyncCatalogRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/database': {
      id: '/database'
      path: '/database'
      fullPath: '/database'
      preLoaderRoute: typeof DatabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card/$cardId': {
      id: '/card/$cardId'
      path: '/card/$cardId'
      fullPath: '/card/$cardId'
      preLoaderRoute: typeof CardCardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/refresh-prices': {
      id: '/api/public/refresh-prices'
      path: '/api/public/refresh-prices'
      fullPath: '/api/public/refresh-prices'
      preLoaderRoute: typeof ApiPublicRefreshPricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-catalog': {
      id: '/api/public/sync-catalog'
      path: '/api/public/sync-catalog'
      fullPath: '/api/public/sync-catalog'
      preLoaderRoute: typeof ApiPublicSyncCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CollectionRoute: CollectionRoute,
  DatabaseRoute: DatabaseRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  ScanRoute: ScanRoute,
  TrendsRoute: TrendsRoute,
  CardCardIdRoute: CardCardIdRoute,
  ApiPublicRefreshPricesRoute: ApiPublicRefreshPricesRoute,
  ApiPublicSyncCatalogRoute: ApiPublicSyncCatalogRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
